### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by sinosoidal** [QUItCoding/qnanopainter#15]
Hi,

I was trying to compile a project that uses qnanopainter on windows and it failed to compile as it couldn't find opengl functions. Is there any additional lib or dependency I must meet to compile this on windows?

Thanks!

**Comment by Kartsaaja** [comment]
Hello,

Yes same problem here.

More specifically 5.7.1 mingw stops at "GLdouble undefined..". In 5.8 mingw the nanovg has problems compiling due to missing openGL(?) functions. So the error is a bit different between 5.7.1, 5.8 it seems.

In 5.7.1 you can make it compile if you edit force typedef for GLdouble in qopenglfunctions.h row 59:
"#ifdef QT_OPENGL_ES
typedef double GLdouble;
#endif"
So only this define is missing for some reason in 5.7.1.

Havent looked in 5.8.

[qnanopainter 5.8 mingw errors.txt](https://github.com/QUItCoding/qnanopainter/files/879470/qnanopainter.5.8.mingw.errors.txt)

**Comment by QUItCoding** [comment]
We've done development & testing mainly on OS X and Android, both working fine with latest Qt versions. Windows worked with Qt 5.6 but haven't tested with newer Qt versions there. If someone familiar with Windows OpenGL would have time to provide a patch that would be great!

**Comment by QUItCoding** [comment]
I think this is fixed also now by #17
